//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserBranches = new HashSet<UserBranch>();
        }
    
        public int UserID { get; set; }
        public string NationalCode { get; set; }
        public string Fname { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string PassWord { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StartActive { get; set; }
        public Nullable<System.DateTime> EndActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBranch> UserBranches { get; set; }
    }
}
